---

- name: Patch server
  ansible.builtin.apt:
    autoremove: true
    upgrade: yes
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    state: present
    name:
      - samba

- name: Configure smb.conf
  ansible.builtin.copy:
    src: files/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    validate: /usr/bin/testparm -s %s
  notify:
        - Restart smbd

- name: Create USB drive mount folder
  ansible.builtin.file:
    path: /mnt/share
    state: directory
  notify:
        - Restart smbd

- name: Add USB drive to /etc/fstab and mount it
  ansible.posix.mount:
    path: /mnt/share
    src: /dev/sda1
    fstype: ext4
    opts: rw,relatime
    state: mounted
  notify:
        - Restart smbd

- name: Set permissions on share root
  ansible.builtin.file:
    path: /mnt/share
    state: directory
    owner: nobody
    group: nogroup
    mode: '2775'

- name: Copy share README
  ansible.builtin.copy:
    src: files/SHARE_README.txt
    dest: /mnt/share/README.txt
    owner: nobody
    group: nogroup
    mode: '0600'

- name: Create share base directories if any
  ansible.builtin.file:
    path: /mnt/share/NEM
    state: directory
    owner: nobody
    group: nogroup
    mode: '2755'

- name: Enable Samba service
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: yes
